fail_fast: false
exclude: "(?:migrations/.*|venv/.*|collected_static/.*|compose/.*|
  docs/.*|logs/.*|media/.*|reports/.*|temp/.*|
  utility/.*|static/.*|templates/.*|test/.*|.idea/.*|.vscode/.*)"
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.12.0]
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-i, --fail-under=50]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master]
      - id: check-yaml
        args: [--unsafe]
        types: [file] # override `types: [json]`
        files: \.(yaml)$
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
