version: '3.8'
services:
  payment:
    build: .
    image: payment_service_image:latest
    container_name: payment_service_image:latest
    command: bash -c "python3 manage.py runserver 0.0.0.0:9000"
    env_file:
      - ./.env
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      replicas: 1
    volumes:
      - .:/app
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:13.0-alpine
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=payment

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data # in ubuntu, in centos, /var/lib/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - network.host=0
      - discovery.type=single-node
      - xpack.security.enabled=false
    depends_on:
      - payment
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/opt/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
volumes:
  postgres_data:
  elasticsearch_data:
